import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DoubleD
 */


public class MyContactsForm extends javax.swing.JFrame {
    
    /**
     * Creates new form MyContactsForm
     */
    String imagePht = null;
    
    public static int currentUserId;
    
    
    public MyContactsForm() {
        initComponents();
        
        populateJtable();
        
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLUE);
        jTable1.setSelectionBackground(Color.lightGray);
        
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.blue);
        th.setFont(new Font("Tahoma", Font.BOLD, 16));
        System.out.println(currentUserId + "From Contact");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUserFoto = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrenume = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldTelefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxGrup = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelFotoProfil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAdresa = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButtonAlegeFisier = new javax.swing.JButton();
        jButtonStergeContact = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAdaugaContact = new javax.swing.JButton();
        jTextFieldNume = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonEditareContact = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("_");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contactele mele");

        jLabelUserFoto.setBackground(new java.awt.Color(255, 255, 0));
        jLabelUserFoto.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabelUserFoto.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabelUserFoto.setOpaque(true);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(102, 0, 204));
        jLabelUsername.setText("Username");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setText("Deconectează-te");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelUserFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMin)
                    .addComponent(jLabelUserFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClose)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(101, 198, 187));
        jPanel2.setPreferredSize(new java.awt.Dimension(436, 240));
        jPanel2.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(236, 240, 241));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Prenume:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 100, 30);

        jLabel5.setBackground(new java.awt.Color(236, 240, 241));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Id:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 20, 40, 30);

        jTextFieldPrenume.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldPrenume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPrenume.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jTextFieldPrenume);
        jTextFieldPrenume.setBounds(120, 100, 220, 30);

        jTextFieldId.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jTextFieldId);
        jTextFieldId.setBounds(120, 20, 220, 30);

        jTextFieldTelefon.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldTelefon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTelefon.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jTextFieldTelefon);
        jTextFieldTelefon.setBounds(120, 140, 220, 30);

        jLabel6.setBackground(new java.awt.Color(236, 240, 241));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Telefon:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 140, 90, 30);

        jTextFieldEmail.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(120, 180, 220, 30);

        jLabel7.setBackground(new java.awt.Color(236, 240, 241));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 180, 70, 30);

        jLabel8.setBackground(new java.awt.Color(236, 240, 241));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Adresa:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(390, 140, 70, 30);

        jComboBoxGrup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGrup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Familie", "Prieteni", "Serviciu" }));
        jPanel2.add(jComboBoxGrup);
        jComboBoxGrup.setBounds(120, 220, 220, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(360, 20, 10, 230);

        jLabel9.setBackground(new java.awt.Color(236, 240, 241));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText("Grup:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 220, 70, 30);

        jLabel10.setBackground(new java.awt.Color(236, 240, 241));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("de profil:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 40, 97, 30);

        jLabelFotoProfil.setBackground(new java.awt.Color(204, 255, 255));
        jLabelFotoProfil.setOpaque(true);
        jPanel2.add(jLabelFotoProfil);
        jLabelFotoProfil.setBounds(470, 20, 140, 110);

        jTextAreaAdresa.setBackground(new java.awt.Color(204, 255, 255));
        jTextAreaAdresa.setColumns(20);
        jTextAreaAdresa.setForeground(new java.awt.Color(0, 0, 102));
        jTextAreaAdresa.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAdresa);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(470, 140, 330, 70);

        jLabel12.setBackground(new java.awt.Color(236, 240, 241));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(44, 62, 80));
        jLabel12.setText("Fotografia ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(370, 20, 97, 30);

        jButtonAlegeFisier.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAlegeFisier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAlegeFisier.setText("Alege fișier");
        jButtonAlegeFisier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlegeFisierActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAlegeFisier);
        jButtonAlegeFisier.setBounds(620, 20, 99, 23);

        jButtonStergeContact.setBackground(new java.awt.Color(255, 51, 51));
        jButtonStergeContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonStergeContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStergeContact.setText("Șterge");
        jButtonStergeContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStergeContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonStergeContact);
        jButtonStergeContact.setBounds(510, 220, 100, 31);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 260, 830, 300);

        jButtonAdaugaContact.setBackground(new java.awt.Color(0, 204, 0));
        jButtonAdaugaContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAdaugaContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdaugaContact.setText("Adaugă");
        jButtonAdaugaContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdaugaContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdaugaContact);
        jButtonAdaugaContact.setBounds(730, 220, 100, 31);

        jTextFieldNume.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldNume.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jTextFieldNume);
        jTextFieldNume.setBounds(120, 60, 220, 30);

        jLabel11.setBackground(new java.awt.Color(236, 240, 241));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 62, 80));
        jLabel11.setText("Nume:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 60, 70, 30);

        jButtonEditareContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonEditareContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEditareContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditareContact.setText("Editare");
        jButtonEditareContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditareContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditareContact);
        jButtonEditareContact.setBounds(620, 220, 100, 31);

        jButtonClear.setBackground(new java.awt.Color(255, 153, 153));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("Clear");
        jButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClearMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonClear);
        jButtonClear.setBounds(390, 220, 110, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void populateJtable(){       
        ContactQuery cq = new ContactQuery();
        ArrayList<Contact> ctList = cq.contactList(currentUserId);
        String[] colNames = {"Id", "Nume", "Prenume", "Grup", "Telefon", "Email", "Adresa", "Imagine"};
        Object[][] rows = new Object[ctList.size()][8];        
        for (int i = 0; i<= ctList.size()-1; i++){
            rows[i][0] =ctList.get(i).getCid();
            rows[i][1] =ctList.get(i).getNume();
            rows[i][2] =ctList.get(i).getPrenume();
            rows[i][3] =ctList.get(i).getGrup();
            rows[i][4] =ctList.get(i).getTelefon();
            rows[i][5] =ctList.get(i).getEmail();
            rows[i][6] =ctList.get(i).getAdresa();            

            
            ImageIcon pic = new ImageIcon(new ImageIcon
                                         (ctList.get(i).getFoto())
                                         .getImage()
                                         .getScaledInstance(140, 110, Image.SCALE_SMOOTH)); 
          
            rows[i][7] = pic;    
   
      
        }
         
        MyModel mmd = new MyModel(rows, colNames);
        jTable1.setModel(mmd);
        jTable1.setRowHeight(110);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(140);
    }
    
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButtonAlegeFisierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlegeFisierActionPerformed
        
        MyFunction mf = new MyFunction();
        imagePht = mf.incarcaFisier(jLabelFotoProfil);
        System.out.println(imagePht);
    }//GEN-LAST:event_jButtonAlegeFisierActionPerformed

    private void jButtonStergeContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStergeContactActionPerformed

        int id = Integer.valueOf(jTextFieldId.getText());
        ContactQuery cq = new ContactQuery();
        cq.deleteContact(id);   
        refreshTable();
        clearFields();
    }//GEN-LAST:event_jButtonStergeContactActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int rowIndex = jTable1.getSelectedRow();
        jTextFieldNume.setText(jTable1.getValueAt(rowIndex, 1).toString());
        jTextFieldPrenume.setText(jTable1.getValueAt(rowIndex, 2).toString());        
        jComboBoxGrup.setSelectedItem(jTable1.getValueAt(rowIndex, 3));
        jTextFieldTelefon.setText(jTable1.getValueAt(rowIndex, 4).toString());
        jTextFieldEmail.setText(jTable1.getValueAt(rowIndex, 5).toString());
        jTextFieldId.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextAreaAdresa.setText(jTable1.getValueAt(rowIndex, 6).toString());        
       Image pic = ((ImageIcon)jTable1.getValueAt(rowIndex, 7)).getImage().getScaledInstance(jLabelFotoProfil.getWidth(), jLabelFotoProfil.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon img = new ImageIcon(pic);
       
       jLabelFotoProfil.setIcon(img);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAdaugaContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdaugaContactActionPerformed
      
        String Nume = jTextFieldNume.getText();
        String Preume = jTextFieldPrenume.getText();
        String Telefon = jTextFieldTelefon.getText();
        String Adresa = jTextAreaAdresa.getText();
        String Email = jTextFieldEmail.getText();
        String GrupC = jComboBoxGrup.getSelectedItem().toString();
        byte [] img = null;
        try {
           
           Path pth = Paths.get(imagePht);
           img=Files.readAllBytes(pth);
        } catch (IOException ex) {
            Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        Contact c = new Contact(null, Nume, Preume, GrupC, Telefon, Email, Adresa, img, currentUserId);
        ContactQuery cq = new ContactQuery();
        cq.insertContact(c);
        refreshTable();
        clearFields();
        
    }//GEN-LAST:event_jButtonAdaugaContactActionPerformed

    public void refreshTable(){
        jTable1.setModel(new DefaultTableModel());
        populateJtable();        
    }
    
    public void clearFields(){
        
        jTextFieldId.setText("");
        jTextFieldNume.setText("");
        jTextFieldPrenume.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelefon.setText("");
        jTextAreaAdresa.setText("");     
        jComboBoxGrup.setSelectedIndex(0);
        jLabelFotoProfil.setIcon(null);
    }
    
    private void jButtonEditareContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditareContactActionPerformed
        
        int Id = Integer.valueOf(jTextFieldId.getText());
        String Nume = jTextFieldNume.getText();
        String Preume = jTextFieldPrenume.getText();
        String Telefon = jTextFieldTelefon.getText();
        String Adresa = jTextAreaAdresa.getText();
        String Email = jTextFieldEmail.getText();
        String GrupC = jComboBoxGrup.getSelectedItem().toString();
        // daca se doreste si editarea imaginii
        if (imagePht != null)
        {
           byte [] img = null;
        try {
           
           Path pth = Paths.get(imagePht);
           img=Files.readAllBytes(pth);
           
           Contact c = new Contact(Id, Nume, Preume, GrupC, Telefon, Email, Adresa, img, currentUserId);
           ContactQuery cq = new ContactQuery();
           cq.editContact(c, true);
           refreshTable();
           clearFields();
        }  catch (IOException ex) {
            Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
        } else{
           Contact c = new Contact(Id, Nume, Preume, GrupC, Telefon, Email, Adresa, null, currentUserId);
           ContactQuery cq = new ContactQuery();
           cq.editContact(c, false);
           refreshTable();
           clearFields();
        }      
         
    }//GEN-LAST:event_jButtonEditareContactActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        loginForm logf = new loginForm();
        logf.setVisible(true);
        logf.pack();
        logf.setLocationRelativeTo(null);
        logf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButtonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClearMouseClicked
         clearFields();
    }//GEN-LAST:event_jButtonClearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new MyContactsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdaugaContact;
    private javax.swing.JButton jButtonAlegeFisier;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonEditareContact;
    private javax.swing.JButton jButtonStergeContact;
    private javax.swing.JComboBox<String> jComboBoxGrup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelFotoProfil;
    private javax.swing.JLabel jLabelMin;
    public javax.swing.JLabel jLabelUserFoto;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAdresa;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNume;
    private javax.swing.JTextField jTextFieldPrenume;
    private javax.swing.JTextField jTextFieldTelefon;
    // End of variables declaration//GEN-END:variables
}
